// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '근로복지공단 푸른씨앗 업무 안내 시스템',
  description: '푸른씨앗 온라인 업무 안내 도우미입니다.',

  openGraph: {
    title: '근로복지공단 푸른씨앗 업무 안내 시스템',
    description: '푸른씨앗 온라인 업무 안내 도우미입니다.',
    url: 'https://comwel.vercel.app',
    siteName: '근로복지공단 푸른씨앗',
    images: [{ url: '000.jpg', width: 1200, height: 630, alt: '푸른씨앗 미리보기 이미지'}],
    type: 'website',
    locale: 'ko_KR',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>{children}</body>
    </html>
  )
}